### PR TITLE
Support camelCase options for all the SassMap keys

### PR DESCRIPTION
**Pull request by shinytang6**
Currently only the topmost key has been applied to camelCase option, but we want all the keys to be applied.
e.g.

converts 

    {
      base-font-color: {
          lightColor: xxx
      }
    }

to

    {
      base-font-color: {
          light-color: xxx
      }
     }

### CODE REVIEW

**Comment by shinytang6** [comment]
hey @adamgruber , can you please take a look?

**Comment by adamgruber** [comment]
@shinytang6 Looks like the CI build failed. Also, can you add a test case for your change? Also, I'm not sure I understand your before/after example above. Seems like they should be swapped and the "after" should have all keys camel case?

**Comment by shinytang6** [comment]
The first one is the current output if the input is a sassmap(of course camelCase:false)
e.g

    $base-font-color: (
          light-color: xxx
    )

l think users want it to be the later one. If you agree the change, l can fix the CI and add the test case!

**Comment by shinytang6** [comment]
Hey @adamgruber, l just updated the test case.

But I'm not sure how to fix ci. It seems to be a problem with node-sass, not my changes.

**Comment by adamgruber** [comment]
@shinytang6 I just pushed some changes to update the dev dependencies and fix the build. Can you rebase your changes? Also, you're missing a new line at the end of the `test/sass/test-opts-camel.scss
` file.

**Comment by shinytang6** [comment]
@adamgruber done.

**Pull request merged**
